package org.fartpig.pagination_sql;

public enum Database {
	CUBRID, DB2, DB2_400, DERBY, ENTERPRISEDB, FIREBIRD, H2, HANA, HSQL_L20, HSQL, INFORMIX, INGRES, INGRES_9, INTERBASE, MYSQL, ORACLE, ORACLE_8, POSTGRESQL, SQLSERVER, TIMESTEN, SQLSERVER2005
}
